### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by markmcdowall** [marcopasi/MuGtoolAPI#2]
Would it be possible to include `setup.py` and `setup.cfg` scripts so that the `mg-tool-api` can be installed using pip. This should make it easier to install the API module within new tools.

`pip install git+https://github.com/Multiscale-Genomics/mg-tool-api.git`

**Comment by marcopasi** [comment]
I think this can now be closed?

**Comment by markmcdowall** [comment]
Done and functioning
